apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ if eq .Values.dev true}}c2{{ else }}c2-live{{ end }}
  name: {{ if eq .Values.dev true}}c2{{ else }}c2-live{{ end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ if eq .Values.dev true}}c2{{ else }}c2-live{{ end }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ if eq .Values.dev true}}c2{{ else }}c2-live{{ end }}
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
