apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: c4
  name: c4
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: c4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: c4
    spec:
      containers:
      {{- include "nimage" .| indent 6 }}
status: {}
