apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: c1
  name: c1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: c1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: c1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
