apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: c1
    app.kubernetes.io/managed-by: Helm
  name: c1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: c1
status:
  loadBalancer: {}
